name: CI macOS Python 3.12

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      runner: macos-latest
      python-version: "3.12"
