name: CI Windows Python 3.13

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      runner: windows-latest
      python-version: "3.13"
